twig:
    file_name_pattern: '*.twig'
    # This line 
    # https://symfony.com/doc/current/form/bootstrap5.html
    form_theme: [ "bootstrap_5_layout.html.twig" ]

when@test:
    twig:
        strict_variables: true
