vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        articles_images:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 
            # https://github.com/dustin10/VichUploaderBundle/blob/master/docs/namers.md#configuration

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            # https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md#step-3-configure-the-lifecycle-events-optional-step

# https://github.com/dustin10/VichUploaderBundle/blob/master/docs/installation.md